# Generated by Django 2.2.3 on 2019-08-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uslugi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='media/uslugi')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
