# Generated by Django 2.2.3 on 2019-08-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uslugi', '0002_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='uslugi',
            name='izo',
            field=models.ImageField(null=True, upload_to='media/uslugi'),
        ),
        migrations.AddField(
            model_name='uslugi',
            name='kek',
            field=models.ImageField(null=True, upload_to='media/uslugi'),
        ),
        migrations.AddField(
            model_name='uslugi',
            name='lol',
            field=models.ImageField(null=True, upload_to='media/uslugi'),
        ),
        migrations.AddField(
            model_name='uslugi',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/uslugi'),
        ),
    ]
