# Generated by Django 2.2.3 on 2019-08-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uslugi', '0003_auto_20190814_0115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Title',
        ),
        migrations.RemoveField(
            model_name='uslugi',
            name='izo',
        ),
        migrations.RemoveField(
            model_name='uslugi',
            name='kek',
        ),
        migrations.RemoveField(
            model_name='uslugi',
            name='lol',
        ),
        migrations.RemoveField(
            model_name='uslugi',
            name='photo',
        ),
        migrations.AddField(
            model_name='uslugi',
            name='price',
            field=models.IntegerField(null=True, verbose_name=10),
        ),
    ]
