# Generated by Django 2.2.3 on 2019-08-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uslugi', '0005_auto_20190815_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uslugi',
            name='price',
            field=models.TextField(null=True),
        ),
    ]
