# Generated by Django 2.2.3 on 2019-08-15 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uslugi', '0006_auto_20190815_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uslugi',
            old_name='price',
            new_name='cena',
        ),
    ]
