# Generated by Django 2.2.3 on 2019-08-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uslugi', '0007_auto_20190815_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uslugi',
            name='cena',
            field=models.IntegerField(null=True),
        ),
    ]
