# Generated by Django 2.2.3 on 2019-08-15 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uslugi', '0008_auto_20190815_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uslugi',
            old_name='cena',
            new_name='price',
        ),
    ]
