# Generated by Django 2.2.3 on 2019-08-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uslugi', '0010_auto_20190815_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uslugi',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
