# Generated by Django 3.0 on 2020-05-18 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primeri', '0002_primerimage_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primerimage',
            name='published_date',
        ),
    ]
