# Generated by Django 2.2.3 on 2019-08-13 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shablon_primer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shablon',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='shablon',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
