# Generated by Django 2.2.3 on 2019-08-13 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shablon_primer', '0002_auto_20190813_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shablon',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='shablon',
            name='published_date',
        ),
    ]
