# Generated by Django 2.2.3 on 2019-08-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shablon_primer', '0003_auto_20190813_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='shablon',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
