# Generated by Django 2.2.3 on 2019-08-16 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shablon_primer', '0004_shablon_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shablon',
            name='published_date',
        ),
    ]
